{
	"version": 1527271611,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/flooring-sheet0.png",
		"images/playerimages-sheet0.png",
		"images/player-sheet0.png",
		"images/banana-sheet0.png",
		"images/mango-sheet0.png",
		"images/strawberry-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/crow-sheet0.png",
		"images/ball-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/creditsboard-sheet0.png",
		"images/playboard-sheet0.png",
		"images/passion-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/particles.png",
		"images/healthbar-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite9-sheet0.png",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/sfx5.m4a",
		"media/sfx5.ogg",
		"media/sword swing.m4a",
		"media/sword swing.ogg",
		"media/gameover1.m4a",
		"media/gameover1.ogg",
		"media/06 jezaig(2).m4a",
		"media/06 jezaig(2).ogg",
		"media/rainforest_ambience-glorysunz-1938133500.m4a",
		"media/rainforest_ambience-glorysunz-1938133500.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"loading-logo.png",
		"icon-256.png"
	]
}